# ===== Stage 1: build react app =====
FROM node:22-alpine AS builder

WORKDIR /app


COPY client/package.json client/yarn.lock ./
RUN yarn install

COPY client/ .
RUN yarn build

# ===== Stage 2: nginx =====
FROM nginx:stable-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# CRA => build
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]