version: "3.8"

services:
  backend:
    build: ./backend
    expose:
      - "6000"
    networks:
      - neuromine-net

  react-app:
    build:
      context: .
      dockerfile: client/Dockerfile.prod
    container_name: react-app
    restart: unless-stopped

    ports:
      - "80:80"
    networks:
      - neuromine-net  

networks:
  neuromine-net:
    driver: bridge